name: Java CI with Gradle

on:
  push:
    branches: [ "konstantinovma" ]
  pull_request:
    branches: [ "konstantinovma" ]
   schedule:
    - cron: '30 12 * * 3'
    - cron: '0 22 * * 5'

permissions:
    contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [11, 17, 21]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.version }}
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      with:
        run: ./gradlew build
